RunConfigurator:
        DetectorConstruction: Sh13DetectorConstruction
#        DetectorConstruction: CloverSimDetectorConstruction
        PhysicsList: PhysicsList
        PrimaryGeneratorAction: PointGammaSourceGeneratorAction
#        PrimaryGeneratorAction: BRIKENGammaSourceGeneratorAction
#        RunAction: LENSLongRunAction
        RunAction: ExN02RunAction
#        EventAction: LENSLongEventAction
#        EventAction: CloverSimEventAction
        EventAction: ExN02EventAction


PointGammaSourceGeneratorAction:
        SourceFile: '152Eu.txt'
#        SourceFile: 'nogamma.txt'
        NEvent: 100000000
#        PositionX: 0.0
#        PositionY: 0.0
#        PositionZ: 0.0 # YSO
#        PositionZ: 6.25 # WASABi DS
#        PositionZ: 39.05 # WASABi US

#PointGammaSourceGeneratorAction:
#        SourceFile: '133Ba.txt'
#        SourceFile: 'nogamma.txt'
#        NEvent: 100000000
#        PositionX: 0.0
#        PositionY: 0.0
#        PositionZ: 0.0 # YSO
#        PositionZ: 6.25 # WASABi DS
#        PositionZ: 39.05 # WASABi US

#PointGammaSourceGeneratorAction:
#        SourceFile: '137Cs.txt'
#        SourceFile: 'nogamma.txt'
#        NEvent: 100000000
#         PositionX: 0.0
#         PositionY: 0.0
#         PositionZ: 0.0 # YSO
#         #PositionZ: 6.25 # WASABi DS
#         #PositionZ: 39.05 # WASABi US

#PointGammaSourceGeneratorAction:
#        SourceFile: '241Am.txt'
#        SourceFile: 'nogamma.txt'
#        NEvent: 100000000
#        PositionX: 0.0
#        PositionY: 0.0
#        PositionZ: 0.0 # YSO
#        PositionZ: 6.25 # WASABi DS
#        PositionZ: 39.05 # WASABi US


#CloverSimAnalysisManager:
#        FileName: './g4sim/CorrelatedEu152YSO_d0.root'
#        FileOption: 'RECREATE'

#CloverSimAnalysisManager:
#        FileName: './g4sim/CorrelatedBa133YSO_d0.root'
#       FileOption: 'RECREATE'

#CloverSimAnalysisManager:
#        FileName: './g4sim/CorrelatedCs137YSO_d0.root'
#        FileOption: 'RECREATE'

#CloverSimAnalysisManager:
#        FileName: './g4sim/CorrelatedAm241YSO_d0.root'
#        FileOption: 'RECREATE'

CloverSimAnalysisManager:
        FileName: '/mnt/c/Users/nakamura_yuki/Desktop/Eu152.root'
        FileOption: 'RECREATE'

#CloverSimAnalysisManager:
#        FileName: '/mnt/c/Users/nakamura yuki/Desktop/Ba133.root'
#        FileOption: 'RECREATE'

#CloverSimAnalysisManager:
#        FileName: '/home/ynakamura/Downloads/Cs137.root'
#        FileName: './Cs137.root'
#        FileOption: 'RECREATE'

#CloverSimAnalysisManager:
#        FileName: '/mnt/c/Users/nakamura yuki/Desktop/Am241.root'
#        FileOption: 'RECREATE'


#ImplantedGammaSourceGeneratorAction:
#        TreeName: mergedData
#        GammaEnergy: 100 # keV
#        BranchName: implantation.
#        PIDGate: True
#        RadA: 15000 # Co74
#        RadB: 3
#        X0: 2.7364
#        Y0: 27.1
#        RadA: 15000 # Ni78
#        RadB: 3
#        X0: 2.7838
#        Y0: 28.1
#        RadA: 18000 # Ga84
#        RadB: 2.5
#        X0: 2.71050
#        Y0: 31.10
#        MergerList:
 #               - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a186_2362_2398_br171106_0528_82Cu_186_171106_0528_82Cu_187bgrun1096_dump.root
 #              - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a154_1810_1848_br171104_1855_82Cu_154_171104_1855_82Cu_155bgrun1078_dump.root
 #               - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a121_1274_1308_br171103_0951_82Cu_121_171103_0951_82Cu_122bgrun1061_dump.root
 #               - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a90_842_865_br171102_0312_82Cu_090_171102_0312_82Cu_091bgrun1046_dump.root
 #               - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a188_2399_2430_br171106_0731_82Cu_188_171106_0731_82Cu_189bgrun1097_dump.root
  #              - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a218_2874_2911_br171107_1250_82Cu_218_171107_1250_82Cu_219bgrun1114_dump.root
  #             - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a123_1309_1347_br171103_1155_82Cu_123_171103_1155_82Cu_124bgrun1062_dump.root
   #             - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a92_866_887_br171102_0512_82Cu_092_171102_0512_82Cu_093bgrun1047_dump.root
    #            - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a190_2431_2466_br171106_0923_82Cu_190_171106_0923_82Cu_191bgrun1098_dump.root
     #           - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a220_2912_2948_br171107_1448_82Cu_220_171107_1448_82Cu_221bgrun1115_dump.root
      #          - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a158_1884_1918_br171104_2312_82Cu_158_171104_2312_82Cu_159bgrun1080_dump.root
       #         - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a125_1348_1371_br171103_1356_82Cu_125_171103_1356_82Cu_126bgrun1063_dump.root
        #       - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a192_2467_2502_br171106_1128_82Cu_192_171106_1128_82Cu_193bgrun1099_dump.root
         #       - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a160_1919_1954_br171105_0115_82Cu_160_171105_0115_82Cu_161bgrun1081_dump.root
        #      - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a96_910_934_br171102_0859_82Cu_096_171102_0859_82Cu_097bgrun1049_dump.root
         #       - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a222_2949_2984_br171107_1647_82Cu_222_171107_1647_82Cu_223bgrun1116_dump.root
          #      - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a127_1372_1406_br171103_1517_82Cu_127_171103_1517_82Cu_128bgrun1064_dump.root
           #     - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a194_2503_2538_br171106_1328_82Cu_194_171106_1328_82Cu_195bgrun1100_dump.root
            #    - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a98_935_959_br171102_1102_82Cu_098_171102_1102_82Cu_099bgrun1050_dump.root
             #   - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a131_1427_1458_br171103_1929_82Cu_131_171103_1929_82Cu_132bgrun1066_dump.root
  #              - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a162_1955_1990_br171105_0316_82Cu_162_171105_0316_82Cu_163bgrun1083_dump.root
  #              - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a224_2986_3023_br171107_1855_82Cu_224_171107_1855_82Cu_225bgrun1117_dump.root
  #              - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a196_2539_2551_br171106_1530_82Cu_196bgrun1101_dump.root
  #              - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a120_1257_1273_br171103_0951_82Cu_122bgrun1060_dump.root
                #   - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a88_818_841_br171102_0114_82Cu_088_171102_0114_82Cu_089bgrun1045_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a100_960_977_br171102_1303_82Cu_100_171102_1303_82Cu_101bgrun1051_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a164_1991_2024_br171105_0516_82Cu_164_171105_0516_82Cu_165bgrun1085_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a133_1459_1494_br171103_2122_82Cu_133_171103_2122_82Cu_134bgrun1067_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a226_3024_3059_br171107_2104_82Cu_226_171107_2104_82Cu_227bgrun1118_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a199_2555_2596_br171106_1716_82Cu_199_171106_1716_82Cu_200bgrun1104_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a104_1014_1049_br171102_1636_82Cu_104_171102_1636_82Cu_105bgrun1053_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a135_1495_1525_br171103_2333_82Cu_135_171103_2333_82Cu_136bgrun1068_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a168_2052_2086_br171105_0911_82Cu_168_171105_0911_82Cu_169bgrun1086_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a228_3060_3093_br171107_2303_82Cu_228_171107_2303_82Cu_229bgrun1119_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a201_2597_2634_br171106_1936_82Cu_201_171106_1936_82Cu_202bgrun1105_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a106_1050_1083_br171102_1838_82Cu_106_171102_1838_82Cu_107_171102_1838_82Cu_109bgrun1054_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a170_2087_2123_br171105_1110_82Cu_170_171105_1110_82Cu_171bgrun1087_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a230_3094_3128_br171108_0102_82Cu_230_171108_0102_82Cu_231bgrun1120_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a137_1526_1562_br171104_0133_82Cu_137_171104_0133_82Cu_138bgrun1069_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a203_2635_2666_br171106_2141_82Cu_203_171106_2141_82Cu_204bgrun1106_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a110_1084_1117_br171102_2036_82Cu_110_171102_2036_82Cu_111bgrun1055_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a172_2124_2157_br171105_1316_82Cu_172_171105_1316_82Cu_173bgrun1088_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a139_1563_1594_br171104_0338_82Cu_139_171104_0338_82Cu_140bgrun1070_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a232_3129_3165_br171108_0304_82Cu_232_171108_0304_82Cu_233bgrun1121_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a205_2667_2696_br171106_2330_82Cu_205_171106_2330_82Cu_206bgrun1107_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a112_1120_1157_br171102_2245_82Cu_112_171102_2245_82Cu_113bgrun1056_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a174_2158_2182_br171105_1516_82Cu_174bgrun1089_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a141_1595_1627_br171104_0533_82Cu_141_171104_0533_82Cu_142bgrun1071_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a207_2697_2726_br171107_0133_82Cu_207_171107_0133_82Cu_208bgrun1108_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a234_3166_3203_br171108_0503_82Cu_234_171108_0503_82Cu_235bgrun1122_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a209_2727_2732_br171107_0330_82Cu_209bgrun1109_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a114_1158_1190_br171103_0047_82Cu_114_171103_0047_82Cu_115bgrun1057_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a175_2183_2219_br171105_1636_82Cu_175_171105_1636_82Cu_176bgrun1090_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a146_1684_1719_br171104_1105_82Cu_146_171104_1105_82Cu_147bgrun1074_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a236_3204_3240_br171108_0702_82Cu_236_171108_0702_82Cu_237bgrun1123_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a210_2733_2766_br171107_0445_82Cu_210_171107_0445_82Cu_211bgrun1110_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a116_1191_1226_br171103_0246_82Cu_116_171103_0246_82Cu_117bgrun1058_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a177_2220_2255_br171105_1837_82Cu_177_171105_1837_82Cu_178bgrun1091_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a102_990_1013_br171102_1435_82Cu_102_171102_1435_82Cu_103bgrun1052_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a150_1735_1773_br171104_1440_82Cu_150_171104_1440_151bgrun1076_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a212_2767_2801_br171107_0645_82Cu_212_171107_0645_82Cu_213bgrun1111_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a118_1227_1256_br171103_0446_82Cu_118_171103_0446_82Cu_119bgrun1059_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a179_2256_2292_br171105_2037_82Cu_179_171105_2037_82Cu_180bgrun1092_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a152_1774_1809_br171104_1651_82Cu_152_171104_1651_82Cu_153bgrun1077_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a214_2802_2835_br171107_0848_82Cu_214_171107_0848_82Cu_215bgrun1112_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a181_2293_2320_br171105_2240_82Cu_181_171105_2240_82Cu_182bgrun1093_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a184_2326_2361_br171106_0320_82Cu_184_171106_0320_82Cu_185bgrun1095_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a216_2836_2873_br171107_1045_82Cu_216_171107_1045_82Cu_217bgrun1113_dump.root
                # - FileName: /SCRATCH/DScratch1/ryokoyam/briken/ur17b/merged_id/mergedfinal_a216_2836_2873_br171107_1045_82Cu_216_171107_1045_82Cu_217bgrun1113_1_dump.root

