#
# Macro file for the initialization phase of "LENS.cc"
#
# Sets some default verbose
#
/control/verbose 2
/run/verbose 2

#/run/initialize

# for drawing the tracks need the following 2 lines
# (if too many tracks cause core dump => storeTrajectory 0)
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate

#/random/resetEngineFrom currentEvent.rndm
#/random/resetEngineFrom beginRandom.rndm
#/random/setSavingFlag true

#/gun/particle gamma
#/gun/position 0 0 0 m
#/gun/particle e-
#/gun/particle e+
#/gun/particle mu+
#/gun/particle neutron

# TEST
#/gun/energy 624 keV
#/tracking/verbose 0
/run/beamOn 100
